# Generated by Django 5.0 on 2025-10-02 16:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(null=True)),
                ('tipe', models.CharField(choices=[('P', 'Personal'), ('O', 'Organizacional')], max_length=1)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('organization_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organizations')),
            ],
        ),
    ]
