# Generated by Django 5.0 on 2025-10-02 16:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsOrganization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('C', 'Creador'), ('A', 'Administrador'), ('M', 'Miembro')], default='M', max_length=1)),
                ('can_complete_tasks', models.BooleanField(default=True)),
                ('can_edit_tasks', models.BooleanField(default=False)),
                ('can_create_tasks', models.BooleanField(default=False)),
                ('can_create_projects', models.BooleanField(default=False)),
                ('can_edit_projects', models.BooleanField(default=False)),
                ('can_invitate', models.BooleanField(default=False)),
                ('can_assign_permissions', models.BooleanField(default=False)),
                ('can_close_organization', models.BooleanField(default=False)),
                ('organization_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations')),
                ('user_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_perm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
