# Generated by Django 5.0 on 2025-10-02 16:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('limit_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('asigned_groups_fk', models.ManyToManyField(blank=True, related_name='asigned_tasks_group', to='groups.groups')),
                ('asigned_users_fk', models.ManyToManyField(blank=True, related_name='asigned_tasks_user', to=settings.AUTH_USER_MODEL)),
                ('previous_task_fd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasks')),
                ('project_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.projects')),
            ],
        ),
    ]
