# Generated by Django 5.0 on 2025-10-02 16:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptada'), ('R', 'Rechazada')], default='P', max_length=1)),
                ('send_date', models.DateField(default=datetime.date.today)),
                ('organization_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations')),
                ('sender_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
