# Generated by Django 5.0 on 2025-10-02 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('members_fk', models.ManyToManyField(related_name='in_groups', to=settings.AUTH_USER_MODEL)),
                ('organization_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organizations.organizations')),
            ],
        ),
    ]
