# Generated by Django 5.0 on 2025-10-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=16, null=True)),
                ('last_name', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
